### ISSUE TITLE
Soccet Error Network unreachable.

### ISSUE THREAD

**Issue by gsettu** [googleads/googleads-python-lib#101]
Hi,
When I go through the OAuth process, I get the following error message “socket.error: [Errno 101] Network is unreachable”.

I did a “echo $http_proxy” / env on the terminal and it returned me http://w1proxy-vip.web1.xxxx.net:3128. That tells me the http proxy is set right.

When I do wget on authorization port ( https://www.googleapis.com/auth/adwords)  I’m getting a “not found Error 404”.  

I have attached the error msg, script and a screenshot of wget/google auth. 

Would appreciate any suggestions on this. 

Here is the error messages:
********************************************************************************************************************
Traceback (most recent call last):
  File "./get_customer_campaign.py", line 35, in <module>
    CLIENT_CUSTOMER_ID)
  File "./get_customer_campaign.py", line 26, in main
    developer_token, oauth2_client, user_agent, client_customer_id,https_proxy='http://w1proxy-vip.we            b1.xxxxx.net:3128')
  File "/home/gsettu/python_virtual_envs/Adwords/lib/python2.7/site-packages/googleads/adwords.py", l            ine 225, in __init__
    self.oauth2_client.Refresh()
  File "/home/gsettu/python_virtual_envs/Adwords/lib/python2.7/site-packages/googleads/oauth2.py", li            ne 164, in Refresh
    self.disable_ssl_certificate_validation)))
  File "/home/gsettu/python_virtual_envs/Adwords/lib/python2.7/site-packages/oauth2client/client.py",             line 633, in refresh
    self._refresh(http.request)
  File "/home/gsettu/python_virtual_envs/Adwords/lib/python2.7/site-packages/oauth2client/client.py",             line 842, in _refresh
    self._do_refresh_request(http_request)
  File "/home/gsettu/python_virtual_envs/Adwords/lib/python2.7/site-packages/oauth2client/client.py",             line 874, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "/home/gsettu/python_virtual_envs/Adwords/lib/python2.7/site-packages/httplib2/__init__.py", l            ine 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, red            irections, cachekey)
  File "/home/gsettu/python_virtual_envs/Adwords/lib/python2.7/site-packages/httplib2/__init__.py", l            ine 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/gsettu/python_virtual_envs/Adwords/lib/python2.7/site-packages/httplib2/__init__.py", l            ine 1272, in _conn_request
    conn.connect()
  File "/home/gsettu/python_virtual_envs/Adwords/lib/python2.7/site-packages/httplib2/__init__.py", l            ine 1075, in connect
    raise socket.error, msg

********************************************************************************************************************
Here is the code in the “get_customer_campaign.py” script

from googleads import adwords
from googleads import oauth2

# OAuth 2.0 credential information. In a real application, you'd probably be
# pulling these values from a credential storage.
CLIENT_ID = ‘xxxx’
CLIENT_SECRET = 'xxxx’
REFRESH_TOKEN = ‘xxxx’

# AdWords API information.
DEVELOPER_TOKEN = ‘xxxx’
USER_AGENT = ‘xxxx’
CLIENT_CUSTOMER_ID = '556-922-8573'

def main(client_id, client_secret, refresh_token, developer_token, user_agent,
             client_customer_id):
  oauth2_client = oauth2.GoogleRefreshTokenClient(
      client_id, client_secret, refresh_token)

  adwords_client = adwords.AdWordsClient(
      developer_token, oauth2_client, user_agent, client_customer_id,https_proxy='http://w1proxy-vip.web1.mlbam.n

  customer = adwords_client.GetService('CustomerService').get()
  print 'You are logged in as customer: %s' % customer['customerId']

if __name__ == '__main__':
  main(CLIENT_ID, CLIENT_SECRET, REFRESH_TOKEN, DEVELOPER_TOKEN, USER_AGENT,
       CLIENT_CUSTOMER_ID)

**Comment by msaniscalchi** [comment]
Hello,

Thanks for reporting. So just to clarify, is this issue restricted to the GoogleRefreshToken client? Are you able to access other content such as the related WSDLs for AdWords?

The Error 404 you're seeing from the wget on https://www.googleapis.com/auth/adwords indicates that you might have some sort of networking issue at play.

I'll see if I can reproduce this and get back to you; I suspect there is some sort of misconfiguration that is causing this.

Regards,
Mark

**Comment by gsettu** [comment]
Hi there, 
I just was able to figure this out. I had to pass the http_proxy in the adwords.client method and it works. 
thanks for the help.
