### ISSUE TITLE
validate_only=True does not work with partial_failures=True

### ISSUE THREAD

**Issue by mikeengland** [googleads/googleads-python-lib#112]
If you set validate_only=True and create an adwords client object with partial_failures=True, exceptions are raised if there are partial failures. The behaviour should be the same whether validate_only is True or False.

Traceback (most recent call last):
  File "/Users/x/x/x-venv/lib/python3.4/site-packages/suds/transport/http.py", line 82, in send
    fp = self.u2open(u2request)
  File "/Users/x/x/x-venv/lib/python3.4/site-packages/suds/transport/http.py", line 132, in u2open
    return url.open(u2request, timeout=tm)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(_args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(_args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/x/x/x-venv/lib/python3.4/site-packages/suds/client.py", line 613, in send
    reply = self.options.transport.send(request)
  File "/Users/x/x/x-venv/lib/python3.4/site-packages/suds/transport/https.py", line 66, in send
    return HttpTransport.send(self, request)
  File "/Users/x/x/x-venv/lib/python3.4/site-packages/suds/transport/http.py", line 94, in send
    raise TransportError(e.msg, e.code, e.fp)
suds.transport.TransportError: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
  File "/Users/x/x/x-venv/lib/python3.4/site-packages/googleads/common.py", line 296, in MakeSoapRequest
    for arg in args])
  File "/Users/x/x/x-venv/lib/python3.4/site-packages/suds/client.py", line 521, in **call**
    return client.invoke(args, kwargs)
  File "/Users/x/x/x-venv/lib/python3.4/site-packages/suds/client.py", line 581, in invoke
    result = self.send(soapenv)
  File "/Users/x/x/x-venv/lib/python3.4/site-packages/suds/client.py", line 619, in send
    description=tostr(e), original_soapenv=original_soapenv)
  File "/Users/x/x/x-venv/lib/python3.4/site-packages/suds/client.py", line 670, in process_reply
    raise WebFault(fault, replyroot)
suds.WebFault: Server raised fault: '[OperatorError.OPERATOR_NOT_SUPPORTED

**Comment by msaniscalchi** [comment]
Hello Mike,

Sorry it took so long to get around to this one. I've verified the behavior you described and have passed this information along to the AdWords team. This is an API issue that we can reproduce in client libraries for other languages as well--it appears that in the presence of both headers, only `validateOnly` will be applied.

Once we reach a resolution on this internally, we'll update the docs to reflect the expected behavior.
