### ISSUE TITLE
socket.error: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by smartfin** [googleads/googleads-python-lib#161]
Using librarary in fresh vagrant box, using ubuntu 16.04.

Just installed library, cloned examples. Filled auth data into yaml file.

But after `python get_account_hierarchy.py`
got such error:
`[2016-11-22 01:10:27,651 - oauth2client.client - INFO] Refreshing access_token
[2016-11-22 01:10:31,169 - suds.transport.http - DEBUG] opening (https://adwords.google.com/api/adwords/mcm/v201609/ManagedCustomerService?wsdl)
Traceback (most recent call last):
  File "get_account_hierarchy.py", line 109, in <module>
    main(adwords_client)
  File "get_account_hierarchy.py", line 56, in main
    'ManagedCustomerService', version='v201609')
  File "/home/vagrant/.local/lib/python2.7/site-packages/googleads/adwords.py", line 356, in GetService
    plugins=[self.message_plugin])
  File "/home/vagrant/.local/lib/python2.7/site-packages/suds/client.py", line 115, in __init__
    self.wsdl = reader.open(url)
  File "/home/vagrant/.local/lib/python2.7/site-packages/suds/reader.py", line 150, in open
    d = self.fn(url, self.options)
  File "/home/vagrant/.local/lib/python2.7/site-packages/suds/wsdl.py", line 136, in __init__
    d = reader.open(url)
  File "/home/vagrant/.local/lib/python2.7/site-packages/suds/reader.py", line 74, in open
    d = self.download(url)
  File "/home/vagrant/.local/lib/python2.7/site-packages/suds/reader.py", line 94, in download
    content = fp.read()
  File "/usr/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
socket.error: [Errno 104] Connection reset by peer`

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report, but I'm unable to reproduce this issue. It looks like this could have potentially been a network issue, are you still seeing this when you attempt to make API calls? I'm not familiar with Vagrant, but your box could be prevented from accessing the API due to some network configuration--e.g. a firewall.

**Comment by smartfin** [comment]
Thanks for your response.
It seems to be bug in Virtualbox 
https://github.com/mitchellh/vagrant/issues/7946
