### ISSUE TITLE
Dealing with unicode control characters

### ISSUE THREAD

**Issue by calvinfo** [googleads/googleads-python-lib#185]
Hey there,

I have a question about how to best deal with unicode control characters. 

We're retrieving results from the Adwords API, but unfortunately, some of them contain '0x10' as a character which breaks the XML parsing of the entire response. Since we're doing this for a variety of reports we don't control, we'd ideally like to strip out these sorts of characters, or at least handle it gracefully (via a flag or otherwise).

Here's what our calling code looks like

```python
ad_group_ad_service.get({'predicates': [{'values': ['37098343321', '37098343801', '33762956816', '33762956856', '37124273939', '37124273979', '38288522878', '38815027601', '38815027641', '39027522214', '42570552120', '37071700967', '37071701007', '40639762008', '40639762048', '34149631580', '41896041988', '32174278943', '32417430414', '33343637957', '34148780820', '34148785620', '34148787300', '34148788980', '34148793340', '36213022791', '36213022991', '37212437201', '38988655088', '41895523908', '41895525548', '41895528388', '41895536548', '41895557668', '33404065822', '33404065902', '34139264859', '34139265019', '34139265059', '34139265099', '35094712235', '35094712275', '35151268698', '35151383738', '36636590826', '36636591026', '36636591106', '36636591306', '37340439040', '37340439240', '37340439320', '37906683249', '37906683329', '38378686535', '38378686735', '38378686935', '39200015171', '40440700041', '32157816165', '33079250785', '30425335101', '32870022879', '33152708306', '33152708346', '33287755363', '33290531973', '33702440076', '34787705986', '35200767353', '35351091804', '36074085560', '36355872398', '36439399827', '37637403750', '40011806858', '40504918064', '40504918224', '41206409234', '42061060748', '40567782424', '32547272046', '32547275486', '32547277126', '32547281206', '33875129455', '33875129495', '33875130175', '33875131335', '33875131415', '33875203095', '33875204615', '34052460136', '34052488456', '34052491856', '34052492536', '34052492816', '34052493256', '34574968075', '34574968515', '34574968755'], 'operator': 'IN', 'field': 'AdGroupId'}], 'paging': {'numberResults': '100', 'startIndex': 0}, 'fields': ['AdGroupId', 'AdType', 'Url', 'Status']}
```

And here's the stacktrace from the response we get back. Happy to provide more info here about the account if that would be useful from a repro perspective

**Stacktrace:**

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 67009

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/adwords/integration/resources/base.py", line 53, in _service_get
    result = self.service.get(selector)
  File "/usr/local/lib/python3.5/dist-packages/googleads/common.py", line 643, in MakeSoapRequest
    for arg in args])
  File "/usr/local/lib/python3.5/dist-packages/suds/client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/suds/client.py", line 581, in invoke
    result = self.send(soapenv)
  File "/usr/local/lib/python3.5/dist-packages/suds/client.py", line 621, in send
    original_soapenv=original_soapenv)
  File "/usr/local/lib/python3.5/dist-packages/suds/client.py", line 661, in process_reply
    replyroot = _parse(reply)
  File "/usr/local/lib/python3.5/dist-packages/suds/client.py", line 832, in _parse
    return Parser().parse(string=string)
  File "/usr/local/lib/python3.5/dist-packages/suds/sax/parser.py", line 133, in parse
    sax.parse(source)
  File "/usr/lib/python3.5/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.5/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.5/xml/sax/expatreader.py", line 214, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python3.5/xml/sax/handler.py", line 38, in fatalError
    raise exception
```

**Client:** 4.7.0
**Runtime:** Python 3.5

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! I'm actually surprised you were able to create ads containing unicode control characters, as I would have expected some validation to prevent that. The suds-jurko library can't parse unicode control characters, which seems to be working as intended. With that in mind, I don't think a change to this library is warranted, but I'll discuss this a bit with the AdWords team.

Regarding your actual question about dealing with this, my initial thoughts are that you could tackle this at the transport level. It should be possible to make a patch that would grab the response data and remove these characters before it is passed along to the parser.

Regards,
Mark

**Comment by msaniscalchi** [comment]
After some further discussion, it definitely is a bug if you were able to create ads with unicode control characters. You should reach out on the [AdWords API Support Forum](https://groups.google.com/forum/#!forum/adwords-api) for additional assistance with this.

Regards,
Mark

**Comment by calvinfo** [comment]
Yeah, that's what we ended up doing. It feels a little dirty, but for anyone running into similar issues, we ended up doing something along the lines of the following:

```python
def monkey_patch():
    from xml.sax import expatreader
    from xml.parsers import expat
    from xml.sax._exceptions import SAXParseException
    CONTROL_CHARS = [chr(i) for i in range(32)]
    replacements = { c: '' for c  in CONTROL_CHARS}
    table = str.maketrans(replacements)

    original_feed = expatreader.ExpatParser.feed
    def feed(self, data, isFinal = 0):
            if isinstance(data, bytes):
                data = data.decode('utf-8', errors='replace')
            data = data.translate(table)
            original_feed(self, data, isFinal)
        
    expatreader.ExpatParser.feed = feed
```

**Comment by calvinfo** [comment]
Got it, thanks @msaniscalchi! It may have been patched at some point, the trouble is that we're running against a bunch of our customers' Adwords installs, so we can't just re-write all the ad objects. We'll keep stripping those characters on read for now.
