### ISSUE TITLE
Error while executing OP-RETURN script using Python3

### ISSUE THREAD

**Issue by satyakamc** [googleads/googleads-python-lib#195]
Hi,

I am trying to execute OP_RETURN script on bitcoind daemon. When I give the command: python3 send-op-return.py "MESSAGE"; get the below response with errors. Hope to get some assistance to resolve this.

Traceback (most recent call last):
  File "send-op-return.py", line 25, in <module>
    spendables = spendables_for_address(bitcoin_address)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pycoin/services/blockchain_info.py", line 37, in spendables_for_address
    r = json.loads(urlopen(URL).read().decode("utf8"))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

**Comment by msaniscalchi** [comment]
Hello,

I suspect you may have typed out your issue into the wrong tab. This is the issue tracker for the Google Ads Python Client library, used for accessing AdWords and DoubleClick for Publisher APIs.

While bitcoin is a fascinating topic, I recommend you ask the owners of the pycoin library for assistance with your issue. :-)

Regards,
Mark
