### ISSUE TITLE
problem with missing attribute '_HttpTransport__get_request_url' in googleads==5.6.0

### ISSUE THREAD

**Issue by veronika-i** [googleads/googleads-python-lib#210]
latest version of googleads python library doesn't work.

I tried to run example https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/v201705/basic_operations/get_campaigns.py
with latest version library from pypi (googleads==5.6.0).

My environment is:
Python 2.7.12 (default, Sep 28 2016, 18:41:32)
```bash
$ pip freeze                                                                                                                  
appnope==0.1.0
backports.shutil-get-terminal-size==1.0.0
decorator==4.0.11
enum34==1.1.6
googleads==5.6.0
httplib2==0.10.3
ipython==5.2.2
ipython-genutils==0.2.0
oauth2client==4.1.0
pathlib2==2.2.1
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.14
ptyprocess==0.5.1
pyasn1==0.2.3
pyasn1-modules==0.0.9
Pygments==2.2.0
PySocks==1.6.7
pytz==2017.2
PyYAML==3.12
rsa==3.4.2
scandir==1.5
simplegeneric==0.8.1
six==1.10.0
suds-jurko==0.7.post1353
traitlets==4.3.2
wcwidth==0.1.7
xmltodict==0.11.0
```
Traceback:
```
(googleads) veronikaiv-mac@/> python get_campaigns.py                                                                                                     
INFO:oauth2client.client:Refreshing access_token
DEBUG:suds.transport.http:opening (https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl)
INFO:googleads.common:Request made.
Traceback (most recent call last):
  File "get_campaigns.py", line 74, in <module>
    main(adwords_client)
  File "get_campaigns.py", line 56, in main
    page = campaign_service.get(selector)
  File "/Users/veronikaiv/googleads/lib/python2.7/site-packages/googleads/common.py", line 731, in MakeSoapRequest
    self._datetime_packer) for arg in args])
  File "/Users/veronikaiv/googleads/lib/python2.7/site-packages/suds/client.py", line 566, in __call__
    return client.invoke(args, kwargs)
  File "/Users/veronikaiv/googleads/lib/python2.7/site-packages/suds/client.py", line 705, in invoke
    result = self.send(soapenv)
  File "/Users/veronikaiv/googleads/lib/python2.7/site-packages/suds/client.py", line 747, in send
    reply = self.options.transport.send(request)
  File "/Users/veronikaiv/googleads/lib/python2.7/site-packages/googleads/util.py", line 99, in PatchedHttpTransportSend
    url = http_transport._HttpTransport__get_request_url(request)
AttributeError: type object 'HttpTransport' has no attribute '_HttpTransport__get_request_url'
```

Patch in quite simple:
in file googleads/util.py change line 99
```url = http_transport._HttpTransport__get_request_url(request)``` 
to
 ```url = http_transport._HttpTransport__get_request_url_for_urllib(request)```

Could you please fix public library?

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! It looks like you're using the latest version of suds-jurko that is still in development, but this library expects the latest stable version (0.6). You can fix this for yourself by using this version as well.

We don't intend to use 0.7 until it is a stable release accessible on PyPI.

Regards,
Mark

**Comment by veronika-i** [comment]
Thank you! 
Examples works good with suds-jurko==0.6

Local pypi server cached just development version of package,
I switched for global pypi server and problem was fixed.
