### ISSUE TITLE
UserService.getCurrentUser gives NETWORK_CODE_REQUIRED Error

### ISSUE THREAD

**Issue by mattpr** [googleads/googleads-python-lib#230]
API `v201708`

According to the pydocs (http://googleads.github.io/googleads-python-lib/):
> network_code: A string identifying the network code of the network you are
      accessing. All requests other than getAllNetworks and getCurrentUser
      calls require this header to be set.

This doesn't seem to be the case anymore?  

```
$ ./dfp.py
Press Ctrl-C to quit.
No handlers could be found for logger "suds.client"
Traceback (most recent call last):
  File "./dfp.py", line 161, in <module>
    main(dfp_client, api_version)
  File "./dfp.py", line 148, in main
    user = getAPIUser(dfp_client, api_version)
  File "./dfp.py", line 32, in getAPIUser
    user = service.getCurrentUser()
  File "/usr/local/lib/python2.7/site-packages/googleads/common.py", line 753, in MakeSoapRequest
    self._datetime_packer) for arg in args])
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 581, in invoke
    result = self.send(soapenv)
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 619, in send
    description=tostr(e), original_soapenv=original_soapenv)
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 670, in process_reply
    raise WebFault(fault, replyroot)
suds.WebFault: Server raised fault: '[AuthenticationError.NETWORK_CODE_REQUIRED @ ]'
```

```
$ python --version
Python 2.7.13
$ pip show googleads
Name: googleads
Version: 8.0.0
Summary: Google Ads Python Client Library
Home-page: https://github.com/googleads/googleads-python-lib
Author: Mark Saniscalchi
Author-email: api.msaniscalchi@gmail.com
License: Apache License 2.0
Location: /usr/local/lib/python2.7/site-packages
Requires: pysocks, PyYAML, httplib2, pytz, suds-jurko, xmltodict, oauth2client
```

**Comment by grivescorbett** [comment]
Thanks for reporting this :). The docs are incorrect, getCurrentUser requires a network code. I'll fix it in the next release.
