### ISSUE TITLE
How to use oauth2.GoogleServiceAccountClient behind a proxy

### ISSUE THREAD

**Issue by kst83** [googleads/googleads-python-lib#244]
I'm having problems getting oauth2.GoogleServiceAccountClient to work behind a proxy.
Is the error on my side, or is this a bug in the library?
My code looks like this:
```    
    https_proxy = common.ProxyConfig.Proxy(host='myproxy.com', port='3128')
    proxy = common.ProxyConfig(https_proxy=https_proxy, http_proxy=https_proxy)
    oauth2_client = oauth2.GoogleServiceAccountClient(oauth2.GetAPIScope('dfp'), SERVICE_ACCOUNT_EMAIL, KEY_FILE,
                                                      proxy_config=proxy)
```

I get the following stack trace:

```
Traceback (most recent call last):
  File "main.py", line 65, in <module>
    main()
  File "main.py", line 60, in main
    get_client()
  File "main.py", line 19, in get_client
    proxy_config=proxy)
  File "C:\Users\klst\AppData\Local\conda\conda\envs\google_afp_env\lib\site-pac
kages\googleads\oauth2.py", line 308, in __init__
    self.Refresh()
  File "C:\Users\klst\AppData\Local\conda\conda\envs\google_afp_env\lib\site-pac
kages\googleads\oauth2.py", line 344, in Refresh
    self.proxy_config.disable_certificate_validation)))
  File "C:\Users\klst\AppData\Local\conda\conda\envs\google_afp_env\lib\site-pac
kages\oauth2client\client.py", line 545, in refresh
    self._refresh(http)
  File "C:\Users\klst\AppData\Local\conda\conda\envs\google_afp_env\lib\site-pac
kages\oauth2client\client.py", line 749, in _refresh
    self._do_refresh_request(http)
  File "C:\Users\klst\AppData\Local\conda\conda\envs\google_afp_env\lib\site-pac
kages\oauth2client\client.py", line 780, in _do_refresh_request
    body=body, headers=headers)
  File "C:\Users\klst\AppData\Local\conda\conda\envs\google_afp_env\lib\site-pac
kages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Users\klst\AppData\Local\conda\conda\envs\google_afp_env\lib\site-pac
kages\httplib2\__init__.py", line 1322, in request
    (response, content) = self._request(conn, authority, uri, request_uri, metho
d, body, headers, redirections, cachekey)
  File "C:\Users\klst\AppData\Local\conda\conda\envs\google_afp_env\lib\site-pac
kages\httplib2\__init__.py", line 1072, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, he
aders)
  File "C:\Users\klst\AppData\Local\conda\conda\envs\google_afp_env\lib\site-pac
kages\httplib2\__init__.py", line 995, in _conn_request
    conn.connect()
  File "C:\Users\klst\AppData\Local\conda\conda\envs\google_afp_env\lib\http\cli
ent.py", line 1392, in connect
    super().connect()
  File "C:\Users\klst\AppData\Local\conda\conda\envs\google_afp_env\lib\http\cli
ent.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\klst\AppData\Local\conda\conda\envs\google_afp_env\lib\socket.p
y", line 724, in create_connection
    raise err
  File "C:\Users\klst\AppData\Local\conda\conda\envs\google_afp_env\lib\socket.p
y", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected
 party did not properly respond after a period of time, or established connectio
n failed because connected host has failed to respond
```

**Comment by grivescorbett** [comment]
It sounds like your proxy isn't responding to the connection attempt. Do you have anything stopping that from happening like a firewall? 

Can you make a connection to that proxy from the same computer with a different application?

**Comment by kst83** [comment]
The computer is behind a firewall, but the proxy port is open.
I'm using the proxy with many other applications without problems.

**Comment by grivescorbett** [comment]
I'm trying to mimic your setup as best as I can given the information I have. One thing I noticed is that I received a slightly different error than yours, but it was resolved by changing the port from a string to an int. Can you give that a try please?

**Comment by kst83** [comment]
Changing the port to an int didn't work either.
For now I've switched to the c# library.

**Comment by grivescorbett** [comment]
Sorry to hear you're still having trouble, if you can provide any more info about your proxy setup, I'm happy to keep investigating. Glad you have a path forward either way!
