### ISSUE TITLE
Unable to connect to AdWords account

### ISSUE THREAD

**Issue by mg-amit** [googleads/googleads-python-lib#261]
Hello, from the samples when I try running account_management/get_account_heirarchy.py, I get the following error.

I'm trying this on Google Cloud Compute server with Anaconda 5.1 with Python 3.6 (64 bit)
I've carefully checked the credentials in the googleads.yaml file, and everything seems to be correct.

I cannot get my head around why this may be happening. Please advise.

```
Traceback (most recent call last):
  File "get_account_hierarchy.py", line 104, in <module>
    main(adwords_client)
  File "get_account_hierarchy.py", line 70, in main
    page = managed_customer_service.get(selector)
  File "/home/amit/anaconda3/lib/python3.6/site-packages/googleads/common.py", line 786, in MakeSoapRequest
    self._header_handler.SetHeaders(self.suds_client)
  File "/home/amit/anaconda3/lib/python3.6/site-packages/googleads/adwords.py", line 566, in SetHeaders
    http_headers = self._adwords_client.oauth2_client.CreateHttpHeader()
  File "/home/amit/anaconda3/lib/python3.6/site-packages/googleads/oauth2.py", line 211, in CreateHttpHeader
    self.Refresh()
  File "/home/amit/anaconda3/lib/python3.6/site-packages/googleads/oauth2.py", line 226, in Refresh
    self.proxy_config.disable_certificate_validation)))
  File "/home/amit/anaconda3/lib/python3.6/site-packages/oauth2client/client.py", line 545, in refresh
    self._refresh(http)
  File "/home/amit/anaconda3/lib/python3.6/site-packages/oauth2client/client.py", line 749, in _refresh
    self._do_refresh_request(http)
  File "/home/amit/anaconda3/lib/python3.6/site-packages/oauth2client/client.py", line 780, in _do_refresh_request
    body=body, headers=headers)
  File "/home/amit/anaconda3/lib/python3.6/site-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/home/amit/anaconda3/lib/python3.6/site-packages/httplib2/__init__.py", line 1513, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cac
hekey)
  File "/home/amit/anaconda3/lib/python3.6/site-packages/httplib2/__init__.py", line 1263, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/amit/anaconda3/lib/python3.6/site-packages/httplib2/__init__.py", line 1186, in _conn_request
    conn.connect()
  File "/home/amit/anaconda3/lib/python3.6/site-packages/httplib2/__init__.py", line 982, in connect
    if self.proxy_info and self.proxy_info.isgood():
AttributeError: 'HTTPSConnectionWithTimeout' object has no attribute 'proxy_info'

```

**Comment by mg-amit** [comment]
Many thanks for your comments @msaniscalchi and @sfontana 
just for everyone's sake, I had the latest version of httplib2 (v0.11.0).  
I first uninstalled `pip uninstall httplib2` from my computer. 
Then, installed an older version with this command `pip install httplib2==0.10.3`
Re-run your sample code again

**Comment by advance512** [comment]
Thanks. I was wondering what I'm missing in Google's OAuth client configuration.. argh
