### ISSUE TITLE
GoogleRefreshTokenClient doesn't seem to correctly refresh a token after an hour of usage

### ISSUE THREAD

**Issue by blubber** [googleads/googleads-python-lib#28]
The following exception is raised after one hour (which, as far as I know is the expiration time on access tokens.)

    Traceback (most recent call last):
      File "", line 118, in <module>
        sys.exit(main(**kwargs))
      File "cli.py", line 415, in main
        dry_run=dry_run
      File "entities.py", line 261, in commit
        self.push_to_google(chunk, settings)
      File "entities.py", line 291, in push_to_google
        response = f(mutations, settings)
      File "entities.py", line 401, in mutate
        return service.mutate(mutations)
      File "client.py", line 60, in mutate
        retval = self.service.mutate(mutations)
      File "/Library/Python/2.7/site-packages/googleads/common.py", line
    231, in MakeSoapRequest
        for arg in args])
      File "/Library/Python/2.7/site-packages/suds/client.py", line 521, in __call__
        return client.invoke(args, kwargs)
      File "/Library/Python/2.7/site-packages/suds/client.py", line 581, in invoke
        result = self.send(soapenv)
      File "/Library/Python/2.7/site-packages/suds/client.py", line 619, in send
        description=tostr(e), original_soapenv=original_soapenv)
      File "/Library/Python/2.7/site-packages/suds/client.py", line 670,
    in process_reply
        raise WebFault(fault, replyroot)
    suds.WebFault: Server raised fault:
    '[AuthenticationError.OAUTH_TOKEN_INVALID @ ; trigger:'<null>']'

A GoogleRefreshtTokenClient instance was created with:

    auth2_client = GoogleRefreshTokenClient(creds['client_id'],
                                            creds['client_secret'],
                                            creds['token']['refresh_token'])

This is running on Python 2.7, with the following package versions:

    googleads==2.0.1
    httplib2==0.9
    oauthlib==0.6.3
    suds-jurko==0.6

The script is trying to run a large set of mutations against the API, it runs ok for exactly an hour each time, then it raises this error.

**Comment by msaniscalchi** [comment]
When we switched to oauth2client, we took advantage of a feature that allows us to refresh approximately five minutes before access token expiry. This should no longer be an issue.

**Comment by stefantcristian** [comment]
This issue has happened to me now and can't get over it. Could you explain please ? 

sudo python mftraffic.py 
No handlers could be found for logger "suds.resolver"
Traceback (most recent call last):
  File "mftraffic.py", line 130, in <module>
    main(adwords_client)
  File "mftraffic.py", line 82, in main
    estimates = traffic_estimator_service.get(selector)
  File "/usr/local/lib/python2.7/dist-packages/googleads/common.py", line 296, in MakeSoapRequest
    for arg in args])
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 581, in invoke
    result = self.send(soapenv)
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 619, in send
    description=tostr(e), original_soapenv=original_soapenv)
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 670, in process_reply
    raise WebFault(fault, replyroot)
suds.WebFault: Server raised fault: '[AuthenticationError.CLIENT_CUSTOMER_ID_IS_REQUIRED @ ; trigger:'<null>']'

**Comment by msaniscalchi** [comment]
Hello,

This is not related to the bug you reopened. A cursory glance seems to indicate that this is related to the Service you're attempting to use requiring a Client Customer Id. My guess is that you probably didn't specify one in the googleads.yaml file. If that's not the case though, follow up with some more details and I'll take a closer look.

**Comment by stefantcristian** [comment]
Hi, thanks for your time, great support :D 

I've followed some new videos on Google Developers YouTube Channel and I sorted it out. It turn out that I needed both a developer token on my existing account and a new MCC test account. Thanks for your help :)
