### ISSUE TITLE
v201805/publisher_query_language_service/get_geo_targets.py doesn't work

### ISSUE THREAD

**Issue by eyedar** [googleads/googleads-python-lib#286]
When I run get_get_targets.py against our DFP instance, I get the following:

> Traceback (most recent call last):
  File "getGeoTargeting.py", line 53, in <module>
    main(dfp_client, GEO_TARGET_TYPE)
  File "getGeoTargeting.py", line 45, in main
    geo_pql_query, geo_data_file, {'type': geo_target_type})
  File "/Library/Python/2.7/site-packages/googleads/dfp.py", line 477, in DownloadPqlResultToCsv
    self._PageThroughPqlSet(pql_query, pql_writer.writerow, values)
  File "/Library/Python/2.7/site-packages/googleads/dfp.py", line 539, in _PageThroughPqlSet
    response = pql_service.select(filter_statement.ToStatement())
  File "/Library/Python/2.7/site-packages/googleads/common.py", line 617, in MakeSoapRequest
    for arg in args])
  File "/Library/Python/2.7/site-packages/suds/client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "/Library/Python/2.7/site-packages/suds/client.py", line 576, in invoke
    soapenv = binding.get_message(self.method, args, kwargs)
  File "/Library/Python/2.7/site-packages/suds/bindings/binding.py", line 109, in get_message
    content = self.bodycontent(method, args, kwargs)
  File "/Library/Python/2.7/site-packages/suds/bindings/document.py", line 95, in bodycontent
    add_param, self.options().extraArgumentErrors)
  File "/Library/Python/2.7/site-packages/suds/argparser.py", line 83, in parse_args
    return arg_parser(args, kwargs, extra_parameter_errors)
  File "/Library/Python/2.7/site-packages/suds/argparser.py", line 108, in __call__
    self.__process_parameters()
  File "/Library/Python/2.7/site-packages/suds/argparser.py", line 299, in __process_parameters
    self.__process_parameter(*pdef)
  File "/Library/Python/2.7/site-packages/suds/argparser.py", line 294, in __process_parameter
    self.__in_choice_context(), value)
  File "/Library/Python/2.7/site-packages/suds/bindings/document.py", line 86, in add_param
    p = self.mkparam(method, pdef, value)
  File "/Library/Python/2.7/site-packages/suds/bindings/document.py", line 130, in mkparam
    return Binding.mkparam(self, method, pdef, object)
  File "/Library/Python/2.7/site-packages/suds/bindings/binding.py", line 225, in mkparam
    return marshaller.process(content)
  File "/Library/Python/2.7/site-packages/suds/mx/core.py", line 59, in process
    self.append(document, content)
  File "/Library/Python/2.7/site-packages/suds/mx/core.py", line 72, in append
    self.appender.append(parent, content)
  File "/Library/Python/2.7/site-packages/suds/mx/appender.py", line 88, in append
    appender.append(parent, content)
  File "/Library/Python/2.7/site-packages/googleads/util.py", line 42, in PatchedAppend
    suds.mx.appender.Appender.append(self, child, cont)
  File "/Library/Python/2.7/site-packages/suds/mx/appender.py", line 168, in append
    self.marshaller.append(parent, content)
  File "/Library/Python/2.7/site-packages/suds/mx/core.py", line 72, in append
    self.appender.append(parent, content)
  File "/Library/Python/2.7/site-packages/suds/mx/appender.py", line 88, in append
    appender.append(parent, content)
  File "/Library/Python/2.7/site-packages/googleads/util.py", line 42, in PatchedAppend
    suds.mx.appender.Appender.append(self, child, cont)
  File "/Library/Python/2.7/site-packages/suds/mx/appender.py", line 168, in append
    self.marshaller.append(parent, content)
  File "/Library/Python/2.7/site-packages/suds/mx/core.py", line 71, in append
    if self.start(content):
  File "/Library/Python/2.7/site-packages/suds/mx/literal.py", line 86, in start
    raise TypeNotFound(content.tag)
suds.TypeNotFound: Type not found: 'type'

I run scripts that I've written against our instance all the time. Is there anything that needs to be done within my instance to make this script work? Thanks.

**Comment by eyedar** [comment]
Also I see no documentation for the `GetDataDownloader` referenced herein. Can you point me to the docs?

**Comment by grivescorbett** [comment]
Hi,

The docs for `GetDataDownloader` are just in the [docstring](https://github.com/googleads/googleads-python-lib/blob/master/googleads/dfp.py#L312). This doesn't look like a client library bug to me as I haven't been able to reproduce it. Feel free to reopen if you disagree but otherwise please direct your question to the [DFP API Google Group](https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api).
