### ISSUE TITLE
First Init Error

### ISSUE THREAD

**Issue by santiruffino** [googleads/googleads-python-lib#297]
I just installed all the requirements and deployed the application. But when I started (for the first time), I get the following error.

`
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/b93f87cfaa0115e5_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/b93f87cfaa0115e5_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/b93f87cfaa0115e5_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 96, in LoadObject
    __import__(cumulative_path)
  File "/base/data/home/apps/i~app-api-adwords/v1.410909144721414617/demo/main.py", line 24, in <module>
    from views import AddAdGroup
  File "/base/data/home/apps/i~app-api-adwords/v1.410909144721414617/views/__init__.py", line 20, in <module>
    from add_adgroup_view import AddAdGroup
  File "/base/data/home/apps/i~app-api-adwords/v1.410909144721414617/views/add_adgroup_view.py", line 22, in <module>
    from handlers.api_handler import APIHandler
  File "/base/data/home/apps/i~app-api-adwords/v1.410909144721414617/handlers/api_handler.py", line 23, in <module>
    from googleads.adwords import AdWordsClient
  File "/base/data/home/apps/i~app-api-adwords/v1.410909144721414617/lib/googleads/__init__.py", line 17, in <module>
    from .adwords import AdWordsClient
  File "/base/data/home/apps/i~app-api-adwords/v1.410909144721414617/lib/googleads/adwords.py", line 577
    class AbstractResponseParser(object, metaclass=abc.ABCMeta):
                                                  ^
SyntaxError: invalid syntax
`

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! At a glance, it looks like you're running this with App Engine? Is this referring to the [App Engine demo](https://github.com/googleads/googleads-python-lib/tree/master/examples/adwords/adwords_appengine_demo)?

You stacktrace seems to be referring to Python 3 code given how the metaclass is specified--that would certainly be a syntax error if run in Python 2. Code in this repository is written in Python 2, so you can see that we have the correct Python 2 implementation [here](https://github.com/googleads/googleads-python-lib/blob/master/googleads/adwords.py#L633).

It sounds like you may have somehow provided the Python 3 version of the googleads library to your appengine app.

Regards,
Mark

**Comment by santiruffino** [comment]
Thanks for the reply! The problem was that he was using PIP being that the PATH was in Python 3. Then when it mattered, he did it wrong.
I had to add PIP2 to the PATH, re-import the project, and there it worked correctly
