### ISSUE TITLE
demo syntax error

### ISSUE THREAD

**Issue by andro19951** [googleads/googleads-python-lib#329]
Hi. Every time I try to run googleads demo in cloud, I get this error. basically I do not change anything and just do the same steps as explained in Readme.md 

Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 96, in LoadObject
    __import__(cumulative_path)
  File "/base/data/home/apps/h~example-123456/v1.412798313800136443/demo/main.py", line 24, in <module>
    from views import AddAdGroup
  File "/base/data/home/apps/h~example-123456/v1.412798313800136443/views/__init__.py", line 20, in <module>
    from .add_adgroup_view import AddAdGroup
  File "/base/data/home/apps/h~example-123456/v1.412798313800136443/views/add_adgroup_view.py", line 22, in <module>
    from handlers.api_handler import APIHandler
  File "/base/data/home/apps/h~example-123456/v1.412798313800136443/handlers/api_handler.py", line 23, in <module>
    from googleads.adwords import AdWordsClient
  File "/base/data/home/apps/h~example-123456/v1.412798313800136443/lib/googleads/__init__.py", line 17, in <module>
    from .adwords import AdWordsClient
  File "/base/data/home/apps/h~example-123456/v1.412798313800136443/lib/googleads/adwords.py", line 577
    class AbstractResponseParser(object, metaclass=abc.ABCMeta):
                                                  ^
SyntaxError: invalid syntax

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report!  It looks like you're installing the googleads library following **2to3** conversion to App Engine. Given that App Engine is using Python 2, it makes sense that there's a syntax error because metaclasses are handled differently between the two versions, as exemplified via the interpreter output below.

Python 2:
```python
Python 2.7.13 (default, xxx) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import abc
>>> class AbstractResponseParser(object, metaclass=abc.ABCMeta):
  File "<stdin>", line 1
    class AbstractResponseParser(object, metaclass=abc.ABCMeta):
                                                  ^
SyntaxError: invalid syntax
```

Python 3:
```python
Python 3.5.3 (default, xxx) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import abc
>>> class AbstractResponseParser(object, metaclass=abc.ABCMeta):
...   pass
```

Regards,
Mark
