### ISSUE TITLE
googleads.errors.GoogleAdsServerFault: [CustomerSyncError.MISSING_IDS @ selector.campaignIds]

### ISSUE THREAD

**Issue by divyaa3011** [googleads/googleads-python-lib#356]
Hi, 
While running get_account_changes.py I am facing this error

Your default encoding, cp1252, is not UTF-8. Please run this script with UTF-8 encoding to avoid errors.
Error summary: {'faultMessage': '[CustomerSyncError.MISSING_IDS @ selector.campaignIds]', 'requestId': '00057d34e8d394e80abc6a094004d560', 'serviceName': 'CustomerSyncService', 'methodName': 'get', 'operations': '1', 'responseTime': '291'}
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\googleads\common.py", line 1382, in MakeSoapRequest
    *packed_args, _soapheaders=soap_headers)['body']['rval']
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\zeep\proxy.py", line 42, in __call__
    self._op_name, args, kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\zeep\wsdl\bindings\soap.py", line 132, in send
    return self.process_reply(client, operation_obj, response)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\zeep\wsdl\bindings\soap.py", line 194, in process_reply
    return self.process_error(doc, operation)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\zeep\wsdl\bindings\soap.py", line 299, in process_error
    detail=fault_node.find('detail'))
zeep.exceptions.Fault: [CustomerSyncError.MISSING_IDS @ selector.campaignIds]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_account_changes.py", line 101, in <module>
    main(adwords_client)
  File "get_account_changes.py", line 60, in main
    account_changes = customer_sync_service.get(selector)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\googleads\common.py", line 1394, in MakeSoapRequest
    e.detail, errors=error_list, message=e.message)
googleads.errors.GoogleAdsServerFault: [CustomerSyncError.MISSING_IDS @ selector.campaignIds]

Please help me with this. A little urgent

**Comment by BenRKarl** [comment]
Hi @divyaa3011 I'm sorry it took so long for us to respond here. Are you still having this problem?
