### ISSUE TITLE
AttributeError: 'module' object has no attribute 's'

### ISSUE THREAD

**Issue by STANAPI** [googleads/googleads-python-lib#374]
Why am I getting the error below when running Adwords report?

Traceback (most recent call last):
  File "main.py", line 33, in <module>
    from googleads import adwords
  File "C:\STB\STAN_PMDA_API\Adwords\googleads\__init__.py", line 17, in <module
>
    from ad_manager import AdManagerClient
  File "C:\STB\STAN_PMDA_API\Adwords\googleads\ad_manager.py", line 28, in <modu
le>
    import googleads.common
  File "C:\STB\STAN_PMDA_API\Adwords\googleads\common.py", line 44, in <module>
    import zeep
  File "C:\Python27\lib\site-packages\zeep-3.2.0-py2.7.egg\zeep\__init__.py", li
ne 1, in <module>
    from zeep.client import CachingClient, Client  # noqa
  File "C:\Python27\lib\site-packages\zeep-3.2.0-py2.7.egg\zeep\client.py", line
 2, in <module>
    from zeep.settings import Settings
  File "C:\Python27\lib\site-packages\zeep-3.2.0-py2.7.egg\zeep\settings.py", li
ne 7, in <module>
    @attr.s(slots=True)
AttributeError: 'module' object has no attribute 's'

**Comment by christopherseeley** [comment]
The AdWords API has been turned down and replaced by the Google Ads API:
https://github.com/googleads/google-ads-python
