### ISSUE TITLE
getting error zeep.exceptions.TransportError: Server returned response (200) with invalid XML

### ISSUE THREAD

**Issue by pratiksha-cobiro** [googleads/googleads-python-lib#376]
Trying to run 
https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/v201809/account_management/get_account_hierarchy.py

to get hierarchy of account.

Getting this Zeep exception:

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zeep/loader.py", line 50, in parse_xml
    forbid_entities=settings.forbid_entities)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/defusedxml/lxml.py", line 143, in fromstring
    rootelement = _etree.fromstring(text, parser, base_url=base_url)
  File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1765, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: PCDATA invalid Char value 8, line 1, column 28269

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zeep/wsdl/bindings/soap.py", line 170, in process_reply
    doc = parse_xml(content, self.transport, settings=client.settings)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zeep/loader.py", line 54, in parse_xml
    content=content
zeep.exceptions.XMLSyntaxError: Invalid XML content received (PCDATA invalid Char value 8, line 1, column 28269)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "utils/account_hierarchy.py", line 117, in <module>
    main(adwords_client)
  File "utils/account_hierarchy.py", line 57, in main
    page = managed_customer_service.get(selector)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/googleads/common.py", line 1377, in MakeSoapRequest
    *packed_args, _soapheaders=soap_headers)['body']['rval']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zeep/proxy.py", line 42, in __call__
    self._op_name, args, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zeep/wsdl/bindings/soap.py", line 132, in send
    return self.process_reply(client, operation_obj, response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zeep/wsdl/bindings/soap.py", line 176, in process_reply
    content=response.content)
zeep.exceptions.TransportError: Server returned response (200) with invalid XML: Invalid XML content received (PCDATA invalid Char value 8, line 1, column 28269).
Content: b`

**Comment by BenRKarl** [comment]
Hi @pratiksha-cobiro thanks for submitting this question! I'm sorry it took us so long to get back to you. Can you confirm that you're still having this issue? If so, are you running the example code as-is?

**Comment by pratiksha-cobiro** [comment]
Fix for  the above problem

`managed_customer_service = self.client.GetService('ManagedCustomerService', version=self.ADWORDS_VERSION)
        managed_customer_service.zeep_client.settings.strict = False`

**Comment by BenRKarl** [comment]
@pratiksha-cobiro thanks for posting a fix! I'm going to close this issue.
