### ISSUE TITLE
Can't install googleads with pip in python 3.7.3

### ISSUE THREAD

**Issue by airam666** [googleads/googleads-python-lib#419]
whenever I try to install googleads in python 3.7.3 this is the result. All I want is to install googleads and run the examples.

pip install googleads
Collecting googleads
  Using cached https://files.pythonhosted.org/packages/53/d6/f5a757cbf0d277d845c9f902ed776807e55547d72a805066a84442326a02/googleads-20.0.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 2798, in get_entry_map
        ep_map = self._ep_map
      File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 2756, in __getattr__
        raise AttributeError(attr)
    AttributeError: _ep_map
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\FPALAC~1\AppData\Local\Temp\pip-install-51feaf3o\googleads\setup.py", line 116, in <module>
        test_suite='tests')
      File "c:\python37\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "c:\python37\lib\site-packages\setuptools\__init__.py", line 133, in _install_setup_requires
        (k, v) for k, v in attrs.items()
      File "c:\python37\lib\site-packages\setuptools\dist.py", line 444, in __init__
        for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
      File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 656, in <genexpr>
        for entry in dist.get_entry_map(group).values()
      File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 2801, in get_entry_map
        self._get_metadata('entry_points.txt'), self
      File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 2499, in parse_map
        raise ValueError("Entry points must be listed in groups")
    ValueError: Entry points must be listed in groups
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\FPALAC~1\AppData\Local\Temp\pip-install-51feaf3o\googleads\

**Comment by christopherseeley** [comment]
Closing as obsolete since there have been lots of releases and dependency changes since v20.0. Please reopen if this is still an issue.
