### ISSUE TITLE
Issue with Google Search Console  data download from Virtual Machine

### ISSUE THREAD

**Issue by sandipsingha** [googleads/googleads-python-lib#420]
When I am trying to download GSC data from my local machine I am able to do it.
But when I am doing it from remote machine I am experiencing below error.

I tried many things like setting up of proxies
#set HTTP_PROXY=http://user:"passsword@1234"@proxy-web.micron.com:80
#set HTTPS_PROXY=https://user:""passsword@1234"@proxy-web.micron.com:80
and installation of
#pip --trusted-host pypi.python.org install -U channels
#pip install --upgrade google-auth-oauthlib
#pip install --upgrade google-api-python-client

but no luck!!

Below is the error message. i need to do it from remote machine only. If anyone have any info please help me.
C:\ETLROOT\Package\ETLDV_SSINGHA\CPG\GSC>python GSC_History.py --noauth_local_webserver
C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client_helpers.py:255: UserWarning: Cannot access webmasters.dat: No such file or direc
warnings.warn(_MISSING_FILE_MESSAGE.format(filename))

Your browser has been opened to visit:

https://accounts.google.com/o/oauth2/auth?client_id=481482298063-as9asen10brhosglfg1v9humrhe8l2se.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080
oogleapis.com%2Fauth%2Fwebmasters.readonly&access_type=offline&response_type=code

If your browser is on a different machine then exit and re-run this
application with the command-line parameter

--noauth_local_webserver

Traceback (most recent call last):
File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\httplib2_init_.py", line 1501, in conn_request
conn.connect()
File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\httplib2_init.py", line 1270, in connect
address_info = socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM)
File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 748, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11003] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "GSC.py", line 256, in 
main(sys.argv)
File "GSC.py", line 77, in main
scope='https://www.googleapis.com/auth/webmasters.readonly')
File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googleapiclient\sample_tools.py", line 93, in init
credentials = tools.run_flow(flow, storage, flags)
File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client_helpers.py", line 133, in positional_wrapper
return wrapped(*args, **kwargs)
File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\tools.py", line 243, in run_flow
credential = flow.step2_exchange(code, http=http)
File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client_helpers.py", line 133, in positional_wrapper
return wrapped(*args, **kwargs)
File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\client.py", line 2054, in step2_exchange
http, self.token_uri, method='POST', body=body, headers=headers)
File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\transport.py", line 282, in request
connection_type=connection_type)
File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\httplib2_init_.py", line 1926, in request
cachekey,
File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\httplib2_init_.py", line 1595, in request
conn, request_uri, method, body, headers
File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\httplib2_init.py", line 1508, in _conn_request
raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
httplib2.ServerNotFoundError: Unable to find the server at oauth2.googleapis.com

**Comment by christopherseeley** [comment]
This library is for the Google Ad Manager SOAP API, not GSC
