### ISSUE TITLE
error occurs when running upload_image_asset.py

### ISSUE THREAD

**Issue by deerstalker** [googleads/googleads-python-lib#426]
A error occurs when I running the original sample upload_image_asset.py. Any suggestions?
python version: 3.7.4

````
Error summary: {'faultMessage': 'null while invoking public abstract com.google.ads.api.services.campaignmgmt.asset.AssetReturnValue com.google.ads.api.services.campaignmgmt.asset.AssetService.mutate(java.util.List) throws com.google.ads.api.services.common.error.ApiException with params [[com.google.ads.api.services.campaignmgmt.asset.v201809.jaxbgen.AssetOperation@75ca81b1]].', 'requestId': '000590272b6854200a624a907b06ad95', 'serviceName': 'AssetService', 'methodName': 'mutate', 'operations': '0', 'responseTime': '121'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/googleads/common.py", line 992, in MakeSoapRequest
    *packed_args, _soapheaders=soap_headers)['body']['rval']
  File "/usr/local/lib/python3.7/site-packages/zeep/proxy.py", line 45, in __call__
    kwargs,
  File "/usr/local/lib/python3.7/site-packages/zeep/wsdl/bindings/soap.py", line 130, in send
    return self.process_reply(client, operation_obj, response)
  File "/usr/local/lib/python3.7/site-packages/zeep/wsdl/bindings/soap.py", line 195, in process_reply
    return self.process_error(doc, operation)
  File "/usr/local/lib/python3.7/site-packages/zeep/wsdl/bindings/soap.py", line 299, in process_error
    detail=fault_node.find("detail"),
zeep.exceptions.Fault: null while invoking public abstract com.google.ads.api.services.campaignmgmt.asset.AssetReturnValue com.google.ads.api.services.campaignmgmt.asset.AssetService.mutate(java.util.List) throws com.google.ads.api.services.common.error.ApiException with params [[com.google.ads.api.services.campaignmgmt.asset.v201809.jaxbgen.AssetOperation@75ca81b1]].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dongche/Documents/code/googleads-python-lib/examples/adwords/v201809/misc/upload_image_asset.py", line 72, in <module>
    main(adwords_client)
  File "/Users/dongche/Documents/code/googleads-python-lib/examples/adwords/v201809/misc/upload_image_asset.py", line 54, in main
    asset = asset_service.mutate([operation])['value'][0]
  File "/usr/local/lib/python3.7/site-packages/googleads/common.py", line 1004, in MakeSoapRequest
    e.detail, errors=error_list, message=e.message)
googleads.errors.GoogleAdsServerFault: null while invoking public abstract com.google.ads.api.services.campaignmgmt.asset.AssetReturnValue com.google.ads.api.services.campaignmgmt.asset.AssetService.mutate(java.util.List) throws com.google.ads.api.services.common.error.ApiException with params [[com.google.ads.api.services.campaignmgmt.asset.v201809.jaxbgen.AssetOperation@75ca81b1]].
````

**Comment by christopherseeley** [comment]
The AdWords API has been turned down and replaced by the Google Ads API:
https://github.com/googleads/google-ads-python
