### ISSUE TITLE
OAUTH_TOKEN_INVALID when running get_campaigns.py

### ISSUE THREAD

**Issue by quangvuptit** [googleads/googleads-python-lib#444]
Hello everyone!
I have done everything in this repository, when I get fresh token and past into googleads.yaml with these fiels:
```
  developer_token:
  client_id: 
  client_secret:
  refresh_token: 
```
And I get this error
```

This library is being run by an unsupported Python version (3.5.2). In order to benefit from important security improvements and ensure compatibility with this library, upgrade to Python 3.6 or higher.
Error summary: {'methodName': 'get', 'operations': '1', 'faultMessage': "[AuthenticationError.OAUTH_TOKEN_INVALID @ ; trigger:'<null>']", 'requestId': '000598a5026a4e690a62cd8d830dfbf5', 'responseTime': '86', 'serviceName': 'CampaignService'}
Traceback (most recent call last):
  File "/opt/googleads/lib/python3.5/site-packages/googleads/common.py", line 992, in MakeSoapRequest
    *packed_args, _soapheaders=soap_headers)['body']['rval']
  File "/opt/googleads/lib/python3.5/site-packages/zeep/proxy.py", line 45, in __call__
    kwargs,
  File "/opt/googleads/lib/python3.5/site-packages/zeep/wsdl/bindings/soap.py", line 130, in send
    return self.process_reply(client, operation_obj, response)
  File "/opt/googleads/lib/python3.5/site-packages/zeep/wsdl/bindings/soap.py", line 195, in process_reply
    return self.process_error(doc, operation)
  File "/opt/googleads/lib/python3.5/site-packages/zeep/wsdl/bindings/soap.py", line 299, in process_error
    detail=fault_node.find("detail"),
zeep.exceptions.Fault: [AuthenticationError.OAUTH_TOKEN_INVALID @ ; trigger:'<null>']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_campaigns.py", line 68, in <module>
    main(adwords_client)
  File "get_campaigns.py", line 51, in main
    page = campaign_service.get(selector)
  File "/opt/googleads/lib/python3.5/site-packages/googleads/common.py", line 1004, in MakeSoapRequest
    e.detail, errors=error_list, message=e.message)
googleads.errors.GoogleAdsServerFault: [AuthenticationError.OAUTH_TOKEN_INVALID @ ; trigger:'<null>']

```

**Comment by wihl** [comment]
As mentioned in the [README](https://github.com/googleads/googleads-python-lib/blob/master/README.md), 

`NOTE: As of v20.0.0 this library is not compatible with Python versions less than Python 3.6`

From the error log above, you are running Python 3.5.2. Upgrade your version of Python and try again.

**Comment by quangvuptit** [comment]
Thank you so much! I will try python3.6
