### ISSUE TITLE
zeep.exceptions.TransportError: Server returned response (200) with invalid XML

### ISSUE THREAD

**Issue by eeshugerman** [googleads/googleads-python-lib#463]
SDK version: 22.0.0
API version: 201922

(Now that I've posted this I realize I should probably try updating the SDK and API version... will do when I have a chance.)

Running into this trying to pull creative objects. Most requests work fine, but some fail like so:
```
Traceback (most recent call last):
  File "/virtualenvs/dwtools/lib/python3.6/site-packages/zeep/loader.py", line 54, in parse_xml
    forbid_entities=settings.forbid_entities,
  File "/virtualenvs/dwtools/lib/python3.6/site-packages/defusedxml/lxml.py", line 145, in fromstring
    rootelement = _etree.fromstring(text, parser, base_url=base_url)
  File "src/lxml/etree.pyx", line 3235, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1764, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: EndTag: '</' not found, line 1, column 25582

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/virtualenvs/dwtools/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 170, in process_reply
    doc = parse_xml(content, self.transport, settings=client.settings)
  File "/virtualenvs/dwtools/lib/python3.6/site-packages/zeep/loader.py", line 58, in parse_xml
    "Invalid XML content received (%s)" % exc.msg, content=content
zeep.exceptions.XMLSyntaxError: Invalid XML content received (EndTag: '</' not found, line 1, column 25582)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  {{ our code, which calls `CreativeService.getCreativesByStatement` with an `offset` and `limit` }}
  File "/virtualenvs/dwtools/lib/python3.6/site-packages/googleads/common.py", line 992, in MakeSoapRequest
    *packed_args, _soapheaders=soap_headers)['body']['rval']
  File "/virtualenvs/dwtools/lib/python3.6/site-packages/zeep/proxy.py", line 45, in __call__
    kwargs,
  File "/virtualenvs/dwtools/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 130, in send
    return self.process_reply(client, operation_obj, response)
  File "/virtualenvs/dwtools/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 176, in process_reply
    content=response.content,
zeep.exceptions.TransportError: Server returned response (200) with invalid XML: Invalid XML content received (EndTag: '</' not found, line 1, column 25582).
Content: b'<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Header><ResponseHeader xmlns="https://www.google.com/apis/ads/publisher/v201911"><requestId>0c1b9bb968fd1c0c9d6bad72fa6d4fed</requestId><responseTime>693</responseTime></ResponseHeader></soap:Header><soap:Body><getCreativesByStatementResponse xmlns="https://www.google.com/apis/ads/publisher/v201911"><rval><totalResultSetSize>616875</totalResultSetSize><startIndex>247400</startIndex><results xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ImageCreative">{{redacted}}
```

Tried [this](https://github.com/googleads/googleads-python-lib/issues/376#issuecomment-476622874), but it didn't help, (and it doesn't seem like proper fix anyway).

**Comment by eeshugerman** [comment]
Upgrading the API and SDK fixed this.
