### ISSUE TITLE
201502 Traffic Estimator 

### ISSUE THREAD

**Issue by BradRuderman** [googleads/googleads-python-lib#52]
Traffic Estimator doesn't seem to be working with latest adwords version!

```
(adwords)➜  adwords git:(master) ✗ python keyword_estimate.py
Traceback (most recent call last):
  File "keyword_estimate.py", line 28, in <module>
    traffic_estimator_service = adwords_client.GetService('TrafficEstimatorService', version='v201502')
  File "/Users//.virtualenvs/adwords/lib/python2.7/site-packages/googleads/adwords.py", line 262, in GetService
    'Supported versions: %s' % (version, _SERVICE_MAP.keys()))
googleads.errors.GoogleAdsValueError: Unrecognized version of the AdWords API. Version given: v201502 Supported versions: ['v201409', 'v201406']
```

**Comment by BradRuderman** [comment]
Oops didn't have latest version!
