### ISSUE TITLE
AttributeError: 'str' object has no attribute 'keys'

### ISSUE THREAD

**Issue by enman** [googleads/googleads-python-lib#82]
Hello,

Running into this issue while running all the scripts.

Traceback (most recent call last):
  File "C:\googleads-python-lib\examples\dfa\v1_20\get_advertisers.py", l
ine 65, in <module>
    dfa_client = googleads.dfa.DfaClient.LoadFromStorage('C:\googleads-py
thon-lib\googleads.yaml')
  File "build\bdist.win32\egg\googleads\dfa.py", line 85, in LoadFromStor
age
  File "build\bdist.win32\egg\googleads\common.py", line 94, in LoadFromS
torage
AttributeError: 'str' object has no attribute 'keys'

Thanks,
Elliot

**Comment by nicholaschen** [comment]
Hi Elliot,

We don't actually support the DFA GoogleAds branch anymore:

http://googleadsdeveloper.blogspot.com/2015/07/dfa-api-sunset-reminder.html
