### ISSUE TITLE
ManagedCustomerService  - UnicodeDecodeError

### ISSUE THREAD

**Issue by Olmer1st** [googleads/googleads-python-lib#86]
Hi,

I have tried to get result using this selector:
selector = {
            'fields': ['CustomerId', 'CompanyName','CurrencyCode', 'DateTimeZone', 'Name', 'TestAccount', 'CanManageClients']
        }
and got the error below:

Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
  File "build/bdist.linux-x86_64/egg/suds/__init__.py", line 168, in <lambda>
    __str__ = lambda x: unicode(x).encode('utf-8')
  File "build/bdist.linux-x86_64/egg/suds/transport/__init__.py", line 96, in __unicode__
    %s""" % (self.code, self.headers, self.message)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 28657: ordinal not in range(128)
Logged from file http.py, line 89

**Comment by Olmer1st** [comment]
Hi,

any comments?
10x

**Comment by msaniscalchi** [comment]
Hello, sorry it took so long for this to get attention.

There are a few possible explanations. The most common is that your default encoding is set to something other than utf-8. If you attempt to print the response when it contains utf-8 characters, you'll see an error like this. If this were the case, simply setting your encoding to utf-8 should resolve the issue.

I'll be closing this, but feel free to reopen if my suggestion didn't resolve the issue.
